- name: Check if CentrifyDC is installed
  command: "rpm -q CentrifyDC"
  register: centrifydc_check
  ignore_errors: yes

- name: Check if Falcon Sensor is installed
  command: "rpm -q falcon-sensor"
  register: falcon_sensor_check
  ignore_errors: yes

- name: Check CentrifyDC service status (if installed)
  command: "systemctl is-active centrifydc"
  register: centrifydc_status
  when: centrifydc_check.rc == 0
  ignore_errors: yes

- name: Check Falcon Sensor service status (if installed)
  command: "systemctl is-active falcon-sensor"
  register: falcon_sensor_status
  when: falcon_sensor_check.rc == 0
  ignore_errors: yes

- name: Format status info
  set_fact:
    status_info: |
      {{ inventory_hostname }}:
      - CentrifyDC: {{ 'Installed' if centrifydc_check.rc == 0 else 'Not Installed' }} - Status: {{ 'Running' if centrifydc_status.stdout == 'active' else 'Not Running' }}
      - Falcon Sensor: {{ 'Installed' if falcon_sensor_check.rc == 0 else 'Not Installed' }} - Status: {{ 'Running' if falcon_sensor_status.stdout == 'active' else 'Not Running' }}

- name: Append status info to the RPM report file
  lineinfile:
    path: "/tmp/status_report_rpm.txt"
    line: "{{ status_info }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  run_once: false
