- name: Print OS family
  debug:
    msg: "{{ ansible_facts['os_family'] }}"

- name: Include RPM play if appropriate
  include_tasks: rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include DEB play if appropriate
  include_tasks: deb.yml
  when: ansible_facts['os_family'] == "Debian"
