- name: Check if Java is installed
  shell: rpm -q java-11-openjdk
  register: java_check
  changed_when: false
  failed_when: false

- name: Copying OpenJDK file to the server
  copy:
    src: "/tmp/java-11-openjdk-headless.rpm"
    dest: /tmp/

- name: Install Java if not present
  yum:
    name: "/tmp/java-11-openjdk-headless.rpm"
    state: present
    disable_gpg_check: yes
  register: java_install_result

- name: Checking if Snow Agent is installed
  shell: rpm -q snowagent
  register: snowagent_status
  changed_when: false
  failed_when: false

- name: Copy Snow Agent RPM to target server
  copy:
    src: /opt/ansible/files/file_name-x64.rpm
    dest: /tmp/

- name: Install Snow Agent
  yum:
    name: "/tmp/file_name-x64.rpm"
    state: present
    disable_gpg_check: yes
  register: snow_install_result

- name: Ensure http.ssl_capath setting is present in config
  lineinfile:
    path: /opt/snow/snowagent.config
    line: '<Setting Key="http.ssl_capath" value="/etc/ssl/certs/ca-bundle.crt"/>'
    insertafter: '<!-- <Setting Key="http.ssl_verify" value="true"/> -->'
    state: present
    backup: yes

- name: Uncomment http.ssl_verify setting in config
  replace:
    path: /opt/snow/snowagent.config
    regexp: '<!--\s*(<Setting Key="http\.ssl_verify" value="true"\s*/>)\s*-->'
    replace: '(<Setting Key="http.ssl_verify" value="true"/>)'
    backup: yes

- name: Run Snow Agent scan
  shell: /opt/snow/snowagent scan
  register: scan_result
  changed_when: false
  ignore_errors: true

- name: Check Snow Agent scan exit status
  debug:
    msg: "Scan command exited with status {{ scan_result.rc }}"

- name: Skip further execution if scan failed
  meta: end_host
  when: scan_result.rc != 0

- name: Run Snow Agent send
  shell: /opt/snow/snowagent send
  register: send_result
  changed_when: false
  ignore_errors: true

- name: Display send result
  debug:
    msg: "Send successful."
  when: send_result.rc == 0

- name: Display last 10 lines of Snow Agent log if send failed
  shell: tail -n 10 /opt/snow/data/snowagent.log
  register: log_output
  changed_when: false
  when: send_result.rc != 0

- name: Create report file
  set_fact:
    status_info: |
      (( inventory_hostname )):
      - Java Installation: {{ 'Installed by Ansible' if java_install_result.changed else 'Already Present' }}
      - Snow Agent Installation: {{ 'Installed by Ansible' if snow_install_result.changed | default(false) else 'Already present' }}
      - Snow Agent Scan:
          - Scan Exit Status: {{ scan_result.rc }}
          - Scan Output: {{ scan_result.stdout | default('No Output') | indent(2) }}
          - Scan Result: {{ 'Success' if scan_result.rc == 0 else 'Failed' }}
      - Snow Agent Send:
          - Send Exit Status: {{ send_result.rc }}
          - Scan Output: {{ send_result.stdout | default('No Output') | indent(2) }}
          - Send Result: {{ 'Success' if send_result.rc == 0 else 'Failed' }}
      {% if send_result.rc != 0 %}
      - Error Logs:
          {{ log_output.stdout | indent(2) }}
          {% endif %}

      ---------------------------------------------------------------------------------

- name: Appending the status informatipon into the report file
  lineinfile:
    path: "/tmp/snow_report.txt"
    line: "{{ status_info }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  run_once: false

- name: Ensuring if the status report file exists
  stat:
    path: "/tmp/snow_report.txt"
  delegate_to: localhost
  register: status_file
  run_once: true

- name: Removing install files
  file:
  path: "{{ item }}"
  loop:
    - "/tmp/java-11-openjdk-headless.rpm"
    - "/tmp/file_name-x64.rpm"
