- name: Print OS family
  debug:
    msg: "{{ ansible_facts['os_family'] }}"

- name: Include RPM play if appropriate
  include_tasks: rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include DEB play if appropriate
  include_tasks: deb.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Ensure both status files exist before sending email
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ item }}"
    state: touch
  loop:
    - /tmp/status_report_rpm.txt
    - /tmp/status_report_deb.txt

- name: Send email with both status reports
  community.general.mail:
    host: smtp.example.com
    port: 25
    to: "admin@example.com"
    subject: "Ansible System Status Report"
    body: "Attached are the system status reports for RPM and DEB-based servers."
    attach:
      - "/tmp/status_report_rpm.txt"
      - "/tmp/status_report_deb.txt"
  delegate_to: localhost
  run_once: true
